config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dashboard, only: [:show]

  resources :prescriptions, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :physicians, only: [:show, :new, :create, :edit, :update, :destroy]

  authenticated :user do
    root 'dashboards#show', :as => 'user_root'
  end

  root 'welcome_pages#index'

end

app/models/drug.rb
class Drug < ActiveRecord::Base
  has_many :prescriptions

  validates :name, presence: true
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  belongs_to :user
  has_many :prescriptions

  validates :user, presence: true
  validates :name, presence: true
  validates :phone, presence: true
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :user
  belongs_to :physician
  belongs_to :drug

  validates :user, presence: true
  validates :drug, presence: true

  FREQUENCY = [
    'once a day',
    'twice a day',
    'three times a day',
    'four times a day',
    'once a month',
    'once a week',
    'twice a week',
    'three times a week',
    'every other day',
    'every 4 hours',
    'every 6 hours',
    'every 8 hours',
    'every 12 hours',
    'every 4 to 6 hours',
    'every 6 to 8 hours',
    'at bedtime',
    'as needed',
    'as directed'
  ]

  DOSE = [
    '1',
    '1.5',
    '2',
    '2.5',
    '3',
    '3.5',
    '4',
    '4.5',
    '5',
    '5.5',
    '6',
    '6.5',
    '7',
    '7.5',
    '8',
    '8.5',
    '9',
    '9.5',
    '10'
  ]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :prescriptions
  has_many :physicians

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :dob]
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @prescriptions = Prescription.where(user: current_user)
    @physicians = Physician.where(user: current_user)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController

  def show
    @physician = Physician.find(params[:id])
  end

  def new
    @physician = Physician.new
    @user_physicians = Physician.where(user: current_user)
  end

  def create
    @physician = Physician.new(physician_params)
    @physician.user_id = current_user.id

    if @physician.save
      redirect_to root_path
    else
      render action: 'new'
    end
  end

  def edit
    @physician = Physician.find(params[:id])
  end

  def update
    @physician = Physician.find(params[:id])
    if @physician.update(physician_params)
      redirect_to user_root_path
    else
      render action: "edit"
    end
  end

  def destroy
    @physician = Physician.find(params[:id])
    @physician.destroy
    redirect_to user_root_path
  end

  private

  def physician_params
    params.require(:physician).permit(:name, :office, :address, :city, :state, :zip, :phone)
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :authenticate_user!

  def show
    @prescription = Prescription.find(params[:id])
  end

  def new
    @drug = Drug.new
    @prescription = Prescription.new
  end

  def create
    @prescription = Prescription.new(prescription_params)
    @drug = Drug.find_or_initialize_by(drug_params)

    @response = get_drug_data(params[:drug][:name])

    if @response["error"].present?
      flash[:alert] = "Please provide the name of a prescription drug."
      render action: 'new'
    else
      @prescription.drug = @drug
      @prescription.user_id = current_user.id

      if @drug.save && @prescription.save
        redirect_to root_path
      else
        render action: 'new'
      end
      save_api_adverse_reactions
    end
  end

  def edit
    @prescription = Prescription.find(params[:id])
  end

  def update
    @prescription = Prescription.find(params[:id])
    if @prescription.update(prescription_params)
      redirect_to user_root_path
    else
      @prescription_frequency = Prescription::FREQUENCY
      @prescription_dose = Prescription::DOSE
      render action: "edit"
    end
  end

  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy
    redirect_to user_root_path
  end

  private

  def get_drug_data(drug_name)
    HTTParty.get(
      "https://api.fda.gov/drug/event.json?&api_key=L3H3SeWMU19yDPGy4N2pDhUmzbsF8JhnDAGTYH8b&search=patient.drug.openfda.generic_name:#{drug_name}+brand_name:#{drug_name}&count=patient.reaction.reactionmeddrapt.exact&limit=10"
    )
  end

  def save_api_adverse_reactions
    reactions = []
    @response["results"].each do |result|
      reactions << result["term"]
    end
    @drug.update_attribute(:adverse_reactions, reactions)
  end

  def drug_params
    params.require(:drug).permit(:name, :adverse_reactions)
  end

  def prescription_params
    params.require(:prescription).permit(:strength, :quantity, :dose_count, :frequency, :physician_id)
  end
end

app/controllers/welcome_pages_controller.rb
class WelcomePagesController < ApplicationController
  def index
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <p>#{messages}</p>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
  def physician_error_messages!
    return '' if @physician.errors.empty?

    messages = @physician.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: @physician.errors.count,
      resource: @physician.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <p>#{messages}</p>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
  def prescription_error_messages!
    return '' if @prescription.errors.empty?

    messages = @prescription.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: @prescription.errors.count,
      resource: @prescription.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <p>#{messages}</p>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

app/views/dashboards/show.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table table-condensed table-fill">
      <thead>
        <tr>
          <th class="text-left">Medications</th>
        </tr>
      </thead>
      <tbody class="table-hover">
        <% if @prescriptions.empty? %>
          <tr>
            <td>You have not added any prescriptions</td>
          </tr>
        <% else %>
          <% @prescriptions.each do |rx| %>
            <tr>
              <td><%= link_to "#{rx.drug.name} #{rx.strength}", prescription_path(rx) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-6">
    <table class="table table-condensed table-fill">
      <thead>
        <tr>
          <th class="text-left">Physicians</th>
        </tr>
      </thead>
      <tbody class="table-hover">
        <% if @physicians.empty? %>
          <tr>
            <td>You have not added a physician</td>
          </tr>
        <% else %>
          <% @physicians.each do |md| %>
            <tr>
              <td>
                <%= link_to md.name, physician_path(md)  %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedicationTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<% if user_signed_in? %>
<body class="dashboard-background">
<% else %>
<body class="main-page">
<% end %>
  <nav class="navbar" role="navigation">
    <div class="container">
        <div class="col-xs-12 col-md-6 navbar-header">
          <h6><%= link_to "Medication Tracker", root_path, id: "logo" %></h6>
        </div>
        <div class="col-xs-12 col-md-6">
          <ul class="navbar text-right">
            <% if !user_signed_in? %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <% else %>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
    <% if !user_signed_in? %>
    <div class="container-fluid">
    <% else %>
    <div class="container fill">
    <% end %>
      <div class="row">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="row subheader">
          <div class="col-xs-12 col-md-8">
            <div class="col-xs-12 col-md-3 text-center">
              <%= link_to user_root_path do %>
                <%= image_tag("buildings.png", class: "dashboard-icon") %>
                <p>Dashboard</p>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-3 text-center">
              <% if controller.controller_name == 'prescriptions' && controller.action_name == 'show' %>
                <%= link_to edit_prescription_path do %>
                  <%= image_tag("pill-icon.png", class: "dashboard-icon") %>
                  <p>Edit Prescription</p>
                <% end %>
              <% else %>
                <%= link_to new_prescription_path do %>
                  <%= image_tag("pill-icon.png", class: "dashboard-icon") %>
                  <p>Add Prescription</p>
                <% end %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-3 text-center">
              <% if controller.controller_name == 'physicians' && controller.action_name == 'show' %>
                <%= link_to edit_physician_path do %>
                  <%= image_tag("doctor.png", class: "dashboard-icon") %>
                  <p>Edit Physician</p>
                <% end %>
              <% else %>
                <%= link_to new_physician_path do %>
                  <%= image_tag("doctor.png", class: "dashboard-icon") %>
                  <p>Add Physician</p>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-xs-12 col-md-4 text-center user-greeting">
            <p>Welcome, <%= "#{current_user.first_name}" %> <%= "#{current_user.last_name}" %></p>
          </div>
        </div>
      <% end %>
        <%= yield %>
      </div>
</body>

</html>

app/views/physicians/edit.html.erb
<%= physician_error_messages! %>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 form-box">
    <div class="form-top">
      <h3>Edit Physician</h3>

      <div class="form-bottom">

        <%= form_for @physician, html: {id: "sign_up_form"} do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :office, class: "form-control", placeholder: "Office Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
          </div>

          <div class="form-group">
            <%= f.text_field :city, class: "form-control", placeholder: "City" %>
          </div>

          <div class="form-group">
            <%= f.text_field :state, class: "form-control", placeholder: "State" %>
          </div>

          <div class="form-group">
            <%= f.text_field :zip, class: "form-control", placeholder: "Zip Code" %>
          </div>

          <div class="form-group">
            <%= f.text_field :phone, class: "form-control", placeholder: "Phone Number" %>
          </div>

          <div class="actions">
            <%= f.submit "Update", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/physicians/new.html.erb
<%= physician_error_messages! %>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 form-box">
    <div class="form-top">
      <h3>Create Physician</h3>

      <div class="form-bottom">

        <%= form_for @physician, html: {id: "sign_up_form"} do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :office, class: "form-control", placeholder: "Office Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
          </div>

          <div class="form-group">
            <%= f.text_field :city, class: "form-control", placeholder: "City" %>
          </div>

          <div class="form-group">
            <%= f.text_field :state, class: "form-control", placeholder: "State" %>
          </div>

          <div class="form-group">
            <%= f.text_field :zip, class: "form-control", placeholder: "Zip Code" %>
          </div>

          <div class="form-group">
            <%= f.text_field :phone, class: "form-control", placeholder: "Phone Number" %>
          </div>

          <div class="actions">
            <%= f.submit "Add Physician", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/physicians/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <table class="table table-condensed table-fill">
      <thead>
        <tr>
          <th class="text-left"><%= @physician.name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% if !@physician.office.empty? %>
            <td>Office: <%= @physician.office %></td>
          <% end %>
        </tr>
        <tr>
          <% if !@physician.address.empty? && !@physician.city.empty? && !@physician.state.empty? && !@physician.zip.empty? %>
            <td>Address: <%= @physician.address %>, <%= @physician.city %>, <%= @physician.state %> <%= @physician.zip %></td>
          <% end %>
        </tr>
        <tr>
          <td>Phone Number: <%= @physician.phone %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="row text-center ">
  <p id="user-log-in">No longer seeing this physician?</p>
  <p><%= link_to "Delete Physician", physician_path(@physician), method: :delete %></p>
</div>

app/views/prescriptions/edit.html.erb
<%= prescription_error_messages! %>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 form-box">
    <div class="form-top">
      <h3>Edit Prescription</h3>

      <div class="form-bottom">
        <%= form_for @prescription, html: {id: "sign_up_form"} do |f| %>

          <div class="form-group">
            <%= fields_for @prescription.drug do |d| %>
              <%= d.text_field :name, class: "form-control", placeholder: "Drug Name" %>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.text_field :strength, class: "form-control", placeholder: "Drug Strength" %>
          </div>

          <div class="form-group">
            <%= f.text_field :quantity, class: "form-control", placeholder: "Quantity" %>
          </div>

          <div class="form-group">
            <%= f.select :dose_count, Prescription::DOSE, {prompt: "Dose Count"}, {class: "form-control"} %>
          </div>

          <div class="form-group">
            <%= f.select :frequency, Prescription::FREQUENCY, {prompt: "Frequency"}, {:class => "form-control"} %>
          </div>

          <div class="form-group">
            <%= f.collection_select :physician_id, Physician.where(user: current_user), :id, :name, {prompt: "Physician"}, {class: "form-control"} %>
          </div>

          <div class="actions">
            <%= f.submit "Update", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/prescriptions/new.html.erb
<%= prescription_error_messages! %>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 form-box">
    <div class="form-top">
      <h3>Create Prescription</h3>

      <div class="form-bottom">
        <%= form_for @prescription, html: {id: "sign_up_form"} do |f| %>
          <div class="form-group">
            <%= fields_for @drug do |d| %>
              <%= d.text_field :name, class: "form-control", placeholder: "Drug Name" %>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.text_field :strength, class: "form-control", placeholder: "Drug Strength" %>
          </div>

          <div class="form-group">
            <%= f.text_field :quantity, class: "form-control", placeholder: "Quantity" %>
          </div>

          <div class="form-group">
            <%= f.select :dose_count, Prescription::DOSE, {prompt: "Dose Count"}, {class: "form-control"} %>
          </div>

          <div class="form-group">
            <%= f.select :frequency, Prescription::FREQUENCY, {prompt: "Frequency"}, {:class => "form-control"} %>
          </div>

          <div class="form-group">
            <%= f.collection_select :physician_id, Physician.where(user: current_user), :id, :name, {prompt: "Physician"}, {class: "form-control"} %>
          </div>

          <div class="actions">
            <%= f.submit "Add Prescription", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/prescriptions/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <table class="table table-condensed table-fill">
      <thead>
        <tr>
          <th class="text-left"><%= @prescription.drug.name %> <%= @prescription.strength %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Quantity: <%= @prescription.quantity %></td>
        </tr>
        <tr>
          <% if !@prescription.dose_count.empty? && !@prescription.frequency.empty? %>
            <td>Directions: <%= @prescription.dose_count %> <%= @prescription.frequency %></td>
          <% elsif !@prescription.frequency.empty? %>
            <td>Frequency: <%= @prescription.frequency %></td>
          <% end %>
        </tr>
        <tr>
          <% if !@prescription.physician.blank? %>
            <td>Physician: <%= @prescription.physician.name %></td>
          <% else %>
            <td>Physician: You have not selected a physician for this prescription</td>
          <% end %>
        </tr>
        <tr>
              <td>Adverse Reactions: <%= @prescription.drug.adverse_reactions.join(", ").capitalize! %>

              </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="row text-center ">
  <p id="user-log-in">No longer taking this prescription?</p>
  <p><%= link_to "Delete Prescription", prescription_path(@prescription), method: :delete %></p>
</div>

app/views/welcome_pages/index.html.erb
<div class="row">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
     <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag("medication-form.jpg", class: "carousel-image img-responsive") %>
      </div>
      <div class="item">
        <%= image_tag("pills-table.jpg", class: "carousel-image img-responsive") %>
      </div>
      <div class="item">
        <%= image_tag("keyboard-pills.jpg", class: "carousel-image img-responsive") %>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div class="container about-container">
  <div class="row home-about text-center">
    <div class="col-md-12">
      <h2 class="text-about">About</h2>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-4">
      <i class="fa fa-user-md fa-4x" aria-hidden="true"></i>
      <h3>Adverse Reactions</h3>
      <p>Medication Tracker allows you to view reported adverse reactions for each of your prescriptions using the openFDA API.</p>
    </div>
    <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-4">
      <i class="fa fa-list-alt fa-4x" aria-hidden="true"></i>
      <h3>Organize</h3>
      <p>Medication Tracker allows you to organize all of your prescription and physician information in one place.</p>
    </div>
    <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-4">
      <i class="fa fa-tachometer fa-4x" aria-hidden="true"></i>
      <h3>User Dashboard</h3>
      <p>Medication Tracker provides a user friendly dashboard to view all prescriptions and physician details.</p>
    </div>
  </div>
</div>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-12 text-center">
        <p class="home-footer">Medication Tracker was created as a final project at Launch Academy by Jessica Rowland, Copyright &copy; 2016</p>
<script>
    $('.carousel').carousel({
      interval: 5000
    })
</script>